### ISSUE TITLE
Github repo and NPM syncing possible?

### ISSUE THREAD

**Issue by ThomasG77** [yohanboniface/Leaflet.FormBuilder#1]
I want to make a PR for a Kosmtik plugin.
It depends from a Leaflet.FormBuilder version 0.0.6 on NPM e.g [`package.json`](https://github.com/kosmtik/kosmtik/blob/master/package.json#L26)
This tag is not available on the Github repo.
Normal?

To make my PR on Kosmtik side, do I have to update all code (core kosmtik and plugins) to make it work with latest Leaflet.FormBuilder instead?

**Comment by yohanboniface** [comment]
> To make my PR on Kosmtik side, do I have to update all code (core kosmtik and plugins) to make it 
> work with latest Leaflet.FormBuilder instead?

You should just need to `git pull` and then `npm install` to update dependencies.
I'll add tags on github anyway :)

**Comment by yohanboniface** [comment]
Ah OK, now I understand.
I need to update Kosmtik to support 0.1.0. It should be very quick. I'll have a look asap.

**Comment by yohanboniface** [comment]
Done yesterday :)
